#!/usr/bin/env python3
r"""
Render table-f3.tex using macros from table_f3_def.tex, with `_t3` suffix.

Structure (table 3 — 13 columns: ID + 4 groups of 3):
- Row 1 groups: (2-4) Generation time (in sec.) | (5-7) Number of test orders run |
                (8-10) Number of tests run | (11-13) Time to generate and run (in sec.)
- Row 2 leaf headers: ID + repeated (Red. tests, Red. orders, TuscanE) per group.
- Footer (Average row) bolded per cell; no highlighting.
- Highlighting (per data row, ties included): the minimum within each group of three,
    i.e. min of (2,3,4), (5,6,7), (8,9,10), (11,12,13)  -> lower is better.
- Vertical rules between all columns; numeric columns right-aligned.
- Thousands separators in the CSV (e.g. "1,794") are handled for the min comparison
    and printed verbatim by the macros.
"""

from __future__ import annotations
import csv
import re
from pathlib import Path
from typing import List

CSV_PATH = Path("table-f3.csv")
OUT_TEX  = Path("table_f3.tex")

MACRO_SUFFIX = "_t3"  # must match table_f3_def.py

def sanitize_col_key(s: str) -> str:
    s = (s or "").strip()
    s = s.replace("/", " per ").replace(" ", "_")
    s = re.sub(r"[^\w]", "_", s)
    s = re.sub(r"__+", "_", s).strip("_")
    return s or "Col"

def sanitize_base(s: str) -> str:
    s = (s or "").strip().replace(" ", "-")
    s = re.sub(r"[^A-Za-z0-9\-\.]", "", s)
    return s or "row"

def read_rows(path: Path) -> List[List[str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.reader(f))

def col_spec(ncols: int) -> str:
    # First column left-aligned, others right-aligned, with vertical rules between all
    if ncols <= 0:
        return ""
    return "l|" + "|".join("r" for _ in range(ncols - 1))

def to_float(x: str) -> float:
    x = (x or "").strip().replace(",", "")
    try:
        return float(x)
    except ValueError:
        return float("inf")  # non-numeric shouldn't win a minimum

def main() -> None:
    rows = read_rows(CSV_PATH)
    if len(rows) < 3:
        raise ValueError("CSV must include two header rows and at least one data row.")

    header_top, header_bottom = rows[0], rows[1]
    data_rows = [r for r in rows[2:] if not all((c or "").strip() == "" for c in r)]

    # Determine column count robustly
    ncols = max(len(header_top), len(header_bottom), *(len(r) for r in data_rows)) if data_rows else max(len(header_top), len(header_bottom))

    # Build numbered column keys from the second header row.
    # NOTE: table-f3.csv keeps "ID" in the TOP header and leaves the bottom cell blank,
    # so column 0 falls back to header_top -> "ID". Duplicate leaf names get _1,_2,...
    col_keys: List[str] = []
    seen: dict[str, int] = {}
    for i in range(ncols):
        raw = (header_bottom[i] if i < len(header_bottom) and header_bottom[i].strip()
               else (header_top[i] if i < len(header_top) else ""))
        base = sanitize_col_key(raw)
        seen[base] = seen.get(base, 0) + 1
        col_keys.append(f"{base}_{seen[base]}")

    out: List[str] = []
    out.append("% Auto-generated by table_f3_lex.py")
    out.append(r"\begin{table*}")
    out.append(r"\centering")
    out.append(r"\caption{\ProjectTableThirdCaption{}}")
    out.append(r"\vspace{1ex}")
    out.append(r"\postcaptiontablespace")
    out.append(r"\label{table:table3}")
    out.append(r"\resizebox{1\textwidth}{!}{%")
    out.append(fr"\begin{{tabular}}{{{col_spec(ncols)}}}")
    out.append(r"\toprule")

    # ---------- Header row 1: group labels (4 groups of 3) ----------
    out.append(
        r"& \multicolumn{3}{c|}{Generation time (in sec.)} "
        r"& \multicolumn{3}{c|}{Number of test orders run} "
        r"& \multicolumn{3}{c|}{Number of tests run} "
        r"& \multicolumn{3}{c}{Time to generate and run (in sec.)} \\"
    )
    out.append(r"\cmidrule(lr){2-4}")
    out.append(r"\cmidrule(lr){5-7}")
    out.append(r"\cmidrule(lr){8-10}")
    out.append(r"\cmidrule(lr){11-13}")

    # ---------- Header row 2: leaf headers (ID + 4x triplet) ----------
    id_head = (header_bottom[0].strip() if len(header_bottom) > 0 and header_bottom[0].strip() else "ID")
    leaf = [rf"\multicolumn{{1}}{{c|}}{{{id_head}}}"]
    triplet = [r"\multicolumn{1}{c|}{Red. tests}",
               r"\multicolumn{1}{c|}{Full Testsuite}",
               r"\multicolumn{1}{c|}{TuscanE}"]
    # three groups bounded by a vertical rule, then the last group whose final cell has no rule
    leaf += triplet * 3
    leaf += [r"\multicolumn{1}{c|}{Red. tests}",
             r"\multicolumn{1}{c|}{Full Testsuite}",
             r"\multicolumn{1}{c}{TuscanE}"]
    out.append(" & ".join(leaf) + r" \\")
    out.append(r"\midrule")

    # Groups to highlight (0-based data indexes): each triplet
    highlight_groups = [(1, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)]

    # ---------- Body ----------
    last_index = len(data_rows) - 1
    for idx, r in enumerate(data_rows):
        base = sanitize_base(r[0] if len(r) > 0 else "")

        # Average/footer row: bold, no highlighting
        if idx == last_index:
            out.append(r"\midrule")
            bold_cells = []
            for c in range(ncols):
                cell = fr"\Use{{{base}_{col_keys[c]}{MACRO_SUFFIX}}}" if c < len(r) else ""
                bold_cells.append(fr"\textbf{{{cell}}}")
            out.append(" & ".join(bold_cells) + r" \\")
            continue

        # Compute which cells to highlight for this row (ties included)
        vals = [to_float(r[i]) if i < len(r) else float("inf") for i in range(ncols)]
        highlight_idx = set()
        for grp in highlight_groups:
            members = [i for i in grp if i < len(r)]
            if not members:
                continue
            m = min(vals[i] for i in members)
            for i in members:
                if vals[i] == m:
                    highlight_idx.add(i)

        # Emit row
        cells = []
        for c in range(ncols):
            token = fr"\Use{{{base}_{col_keys[c]}{MACRO_SUFFIX}}}" if c < len(r) else ""
            if c in highlight_idx:
                token = fr"\cellcolor{{green!25}}{{{token}}}"
            cells.append(token)
        out.append(" & ".join(cells) + r" \\")

    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append(r"}")
    out.append(r"\end{table*}")

    OUT_TEX.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT_TEX.resolve()}")

if __name__ == "__main__":
    main()