#!/usr/bin/env python3
r"""
Render table-f6.tex using macros from table_f6_def.tex, with `_t6` suffix.

Structure (table 6 — 13 columns: ID + 2 groups of 6):
- Row 1 groups: (2-7) Numbers of orders to detect the 1st OD
               | (8-13) Time (in sec.) to detect the 1st OD
- Row 2 leaf headers: ID + (Red. tests, Full Testsuite, Random, TuscanIC, Pairwise,
  TuscanE) repeated per group.
- Footer: last row ("Average") bolded per cell (no highlighting).
- Highlighting: for every data row (except Average), highlight the minimum within each
  group of six (ties included) using \cellcolor{green!25}{...}; lower = better.
- Vertical rules between all columns; numeric columns right-aligned.
- Decimals and thousands separators (e.g. "16680.7", "1,383,556.4") are handled for the
  min comparison and printed verbatim by the macros.

To DROP the green highlight (as in table 4): delete the two lines marked
"HIGHLIGHT" below; every cell then emits a plain \Use{...}.
"""

from __future__ import annotations
import csv
import re
from pathlib import Path
from typing import List

CSV_PATH = Path("table-f6.csv")
OUT_TEX  = Path("table_f6.tex")

MACRO_SUFFIX = "_t6"  # must match table_f6_def.py

def sanitize_col_key(s: str) -> str:
    s = (s or "").strip()
    s = s.replace("/", " per ").replace(" ", "_")
    s = re.sub(r"[^\w]", "_", s)
    s = re.sub(r"__+", "_", s).strip("_")
    return s or "Col"

def sanitize_base(s: str) -> str:
    s = (s or "").strip().replace(" ", "-")
    s = re.sub(r"[^A-Za-z0-9\-\.]", "", s)
    return s or "row"

def read_rows(path: Path) -> List[List[str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.reader(f))

def col_spec(ncols: int) -> str:
    # |l| then (ncols-1) right-aligned numeric columns with vertical rules
    if ncols <= 0:
        return ""
    return "l|" + "|".join("r" for _ in range(ncols - 1))

def to_float(x: str) -> float:
    x = (x or "").strip().replace(",", "")
    try:
        return float(x)
    except ValueError:
        return float("inf")  # if non-numeric, never wins min

def main() -> None:
    rows = read_rows(CSV_PATH)
    if len(rows) < 3:
        raise ValueError("CSV must include two header rows and at least one data row.")

    header_top, header_bottom = rows[0], rows[1]
    data_rows = [r for r in rows[2:] if not all((c or "").strip() == "" for c in r)]

    # Expect 13 columns total: ID + 12 numeric (2 groups of 6). Compute robustly:
    ncols = max(len(header_top), len(header_bottom), *(len(r) for r in data_rows)) if data_rows else max(len(header_top), len(header_bottom))

    # Build numbered column keys (duplicate leaf names get _1,_2,...). Column 0 has a
    # blank bottom header, so it falls back to the top header -> "ID".
    col_keys: List[str] = []
    seen: dict[str, int] = {}
    for i in range(ncols):
        raw = (header_bottom[i] if i < len(header_bottom) and header_bottom[i].strip()
               else (header_top[i] if i < len(header_top) else ""))
        base = sanitize_col_key(raw)
        seen[base] = seen.get(base, 0) + 1
        col_keys.append(f"{base}_{seen[base]}")

    # Latex output
    out: List[str] = []
    out.append("% Auto-generated by table_f6_lex.py")
    out.append(r"\begin{table*}")
    out.append(r"\centering")
    # Fallback caption; define \ProjectTableSixthCaption in your preamble to override.
    out.append(r"\providecommand{\ProjectTableSixthCaption}{First order-dependent test detection across reduction strategies: number of test orders and wall-clock time (in sec.).}")
    out.append(r"\caption{\ProjectTableSixthCaption{}}")
    out.append(r"\vspace{1ex}")
    out.append(r"\postcaptiontablespace")
    out.append(r"\label{table:table6}")
    # Only shrink if wider than the text width; never enlarge.
    out.append(r"\resizebox{\ifdim\width>\textwidth \textwidth\else\width\fi}{!}{%")
    out.append(fr"\begin{{tabular}}{{{col_spec(ncols)}}}")
    out.append(r"\toprule")

    # ---------- Header row 1 (group labels) ----------
    out.append(r"\multicolumn{1}{c|}{} & \multicolumn{6}{c|}{Numbers of orders to detect the 1st OD} & \multicolumn{6}{c}{Time (in sec.) to detect the 1st OD} \\")
    out.append(r"\cmidrule(lr){2-7}")
    out.append(r"\cmidrule(lr){8-13}")

    # ---------- Header row 2 (leaf headers; ID + two sextets) ----------
    id_head = (header_bottom[0].strip() if len(header_bottom) > 0 and header_bottom[0].strip() else "ID")
    leaf_labels = ["Red. tests", "Full Testsuite", "Random", "TuscanIC", "Pairwise", "TuscanE"]
    leaf = [r"\multicolumn{1}{c|}{" + id_head + "}"]
    leaf += [r"\multicolumn{1}{c|}{" + lbl + "}" for lbl in leaf_labels]          # group 1
    leaf += [r"\multicolumn{1}{c|}{" + lbl + "}" for lbl in leaf_labels[:-1]]     # group 2 (all but last)
    leaf += [r"\multicolumn{1}{c}{" + leaf_labels[-1] + "}"]                       # last cell: no rule
    out.append(" & ".join(leaf) + r" \\")
    out.append(r"\midrule")

    # Highlight groups (inclusive 0-based indexes into the row list; ID is index 0).
    # Group 1 (orders): 1..6   Group 2 (time): 7..12
    groups0 = [(1, 6), (7, 12)]

    # ---------- Body ----------
    last_index = len(data_rows) - 1
    for idx, r in enumerate(data_rows):
        base = sanitize_base(r[0] if len(r) > 0 else "")

        # Average row: bold, no highlighting
        if idx == last_index:
            out.append(r"\midrule")
            bold_cells = []
            for c in range(ncols):
                cell = fr"\Use{{{base}_{col_keys[c]}{MACRO_SUFFIX}}}" if c < len(r) else ""
                bold_cells.append(fr"\textbf{{{cell}}}")
            out.append(" & ".join(bold_cells) + r" \\")
            continue

        # Per-group minima (ties included)
        vals = [to_float(r[i]) if i < len(r) else float("inf") for i in range(ncols)]
        highlight_idx: set[int] = set()
        for (a, b) in groups0:
            g_indices = [i for i in range(a, b + 1) if i < len(r)]
            if not g_indices:
                continue
            g_min = min(vals[i] for i in g_indices)
            for i in g_indices:
                if vals[i] == g_min:
                    highlight_idx.add(i)

        cells = []
        for c in range(ncols):
            token = fr"\Use{{{base}_{col_keys[c]}{MACRO_SUFFIX}}}" if c < len(r) else ""
            if c in highlight_idx:                                    # HIGHLIGHT (delete)
                token = fr"\cellcolor{{green!25}}{{{token}}}"         # HIGHLIGHT (delete)
            cells.append(token)
        out.append(" & ".join(cells) + r" \\")

    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append(r"}")
    out.append(r"\end{table*}")

    OUT_TEX.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT_TEX.resolve()}")

if __name__ == "__main__":
    main()