#!/usr/bin/env python3
r"""
Render table-f5.tex using macros from table_f5_def.tex, with `_t5` suffix.

Structure (table 5):
- Row 1 groups: (2-5) 1st OD Detection Order No | (6-9) 1st OD Detection Time
- Row 2 leaf headers: ID, then (Random, Prior work~\cite{Li2023KLS}, Pairwise, TuscanE) repeated per group.
- Footer: last row ("Average") bolded per cell (no highlighting).
- Highlighting: for EVERY data row (except the last "Average" row),
    highlight the minimum (ties included) in columns 2-5 and 6-9
    using \cellcolor{green!25}{...}  (lower = better for both order-no and time).
- Vertical rules between all columns, numeric columns right-aligned.
"""

from __future__ import annotations
import csv
import re
from pathlib import Path
from typing import List

CSV_PATH = Path("table-f5.csv")
OUT_TEX  = Path("table_f5.tex")

MACRO_SUFFIX = "_t5"  # must match table_f5_def.py

def sanitize_col_key(s: str) -> str:
    s = (s or "").strip()
    s = s.replace("/", " per ").replace(" ", "_")
    s = re.sub(r"[^\w]", "_", s)
    s = re.sub(r"__+", "_", s).strip("_")
    return s or "Col"

def sanitize_base(s: str) -> str:
    s = (s or "").strip().replace(" ", "-")
    s = re.sub(r"[^A-Za-z0-9\-\.]", "", s)
    return s or "row"

def read_rows(path: Path) -> List[List[str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.reader(f))

def col_spec(ncols: int) -> str:
    # |l| then (ncols-1) right-aligned numeric columns with vertical rules
    if ncols <= 0:
        return ""
    return "l|" + "|".join("r" for _ in range(ncols - 1))

def to_float(x: str) -> float:
    x = (x or "").strip().replace(",", "")
    try:
        return float(x)
    except ValueError:
        return float("inf")  # if non-numeric, never wins min

def main() -> None:
    rows = read_rows(CSV_PATH)
    if len(rows) < 3:
        raise ValueError("CSV must include two header rows and at least one data row.")

    header_top, header_bottom = rows[0], rows[1]
    data_rows = [r for r in rows[2:] if not all((c or "").strip() == "" for c in r)]

    # Expect 9 columns total: ID + 8 numeric (2 groups of 4)
    # But compute robustly from data widths:
    ncols = max(len(header_top), len(header_bottom), *(len(r) for r in data_rows)) if data_rows else max(len(header_top), len(header_bottom))

    # Build numbered column keys from bottom headers (supports duplicate names _1,_2,...)
    col_keys: List[str] = []
    seen: dict[str, int] = {}
    for i in range(ncols):
        raw = (header_bottom[i] if i < len(header_bottom) and header_bottom[i].strip()
               else (header_top[i] if i < len(header_top) else ""))
        base = sanitize_col_key(raw)
        seen[base] = seen.get(base, 0) + 1
        col_keys.append(f"{base}_{seen[base]}")

    # Latex output
    out: List[str] = []
    out.append("% Auto-generated by table_f5_lex.py")
    out.append(r"\begin{table*}")
    out.append(r"\centering")
    out.append(r"\caption{\ProjectTableFifthCaption{}}")
    out.append(r"\vspace{1ex}")
    out.append(r"\postcaptiontablespace")
    out.append(r"\label{table:table5}")
    out.append(r"\resizebox{1\textwidth}{!}{%")
    out.append(fr"\begin{{tabular}}{{{col_spec(ncols)}}}")
    out.append(r"\toprule")

    # ---------- Header row 1 (group labels exactly as required) ----------
    # Col 1 is blank cell above "ID" (centred), then two groups of 4:
    out.append(r"\multicolumn{1}{c|}{} & \multicolumn{4}{c|}{1st OD Detection Order No} & \multicolumn{4}{c}{1st OD Detection Time} \\")
    out.append(r"\cmidrule(lr){2-5}")
    out.append(r"\cmidrule(lr){6-9}")

    # ---------- Header row 2 (leaf headers; ID + two quartets) ----------
    id_head = (header_bottom[0].strip() if len(header_bottom) > 0 and header_bottom[0].strip() else "ID")
    leaf = [r"\multicolumn{1}{c|}{" + id_head + "}"] + \
           [r"\multicolumn{1}{c|}{Random}",
            r"\multicolumn{1}{c|}{Prior work~\cite{Li2023KLS}}",
            r"\multicolumn{1}{c|}{Pairwise}",
            r"\multicolumn{1}{c|}{TuscanE}",
            r"\multicolumn{1}{c|}{Random}",
            r"\multicolumn{1}{c|}{Prior work~\cite{Li2023KLS}}",
            r"\multicolumn{1}{c|}{Pairwise}",
            r"\multicolumn{1}{c}{TuscanE}"]
    out.append(" & ".join(leaf) + r" \\")
    out.append(r"\midrule")

    # Compute groups for highlighting.
    # Row lists are 0-based with ID at index 0; numeric columns are 1..8.
    # Group 1 (Detection Order No): CSV indexes 1..4
    # Group 2 (Detection Time):     CSV indexes 5..8
    groups0 = [(1, 4), (5, 8)]  # inclusive 0-based indexes into the row list

    # ---------- Body ----------
    last_index = len(data_rows) - 1
    for idx, r in enumerate(data_rows):
        base = sanitize_base(r[0] if len(r) > 0 else "")

        # If this is the last row (Average), bold all cells (no highlighting)
        if idx == last_index:
            out.append(r"\midrule")
            bold_cells = []
            for c in range(ncols):
                cell = fr"\Use{{{base}_{col_keys[c]}{MACRO_SUFFIX}}}" if c < len(r) else ""
                bold_cells.append(fr"\textbf{{{cell}}}")
            out.append(" & ".join(bold_cells) + r" \\")
            continue

        # Otherwise: compute per-group minima from raw CSV numeric values to decide highlighting
        vals = [to_float(r[i]) if i < len(r) else float("inf") for i in range(ncols)]

        # For each group, find min and all indexes that tie
        highlight_idx: set[int] = set()
        for (a, b) in groups0:
            g_indices = [i for i in range(a, b + 1) if i < len(r)]
            if not g_indices:
                continue
            g_vals = [vals[i] for i in g_indices]
            g_min = min(g_vals)
            for i in g_indices:
                if vals[i] == g_min:
                    highlight_idx.add(i)

        # Emit row: ID plain; groups highlighted for mins (ties included)
        cells = []
        for c in range(ncols):
            token = fr"\Use{{{base}_{col_keys[c]}{MACRO_SUFFIX}}}" if c < len(r) else ""
            if c in highlight_idx:
                cells.append(fr"\cellcolor{{green!25}}{{{token}}}")
            else:
                cells.append(token)
        out.append(" & ".join(cells) + r" \\")

    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append(r"}")
    out.append(r"\end{table*}")

    OUT_TEX.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT_TEX.resolve()}")

if __name__ == "__main__":
    main()